
* jblock - j's adblocker

~jblock~ is a WIP adblocking library for python, created for learning and for
necessity. It was created because [[https://github.com/scrapinghub/adblockparser][adblockparser]] was inefficiently designed, and
because adblocking is a lot more interesting than you might think! Eventually,
this aims to be a possible option for more powerful adblocking for [[https://github.com/qutebrowser/qutebrowser][qutebrowser]].

If you are interested in adblocking, let me know (I hang out in ~#qutebrowser~),
and I might make a blog post talking about adblocking strategies. Unfortunately,
there's very little good recent documentation, and the ubo/abp codebases aren't
very well documented either.

[[https://www.youtube.com/watch?v=Bd29bqfuCSc&feature=youtu.be][Here's a demo, but expect it to be outdated very quickly]].

Don't build anything on this yet, I expect to redo the API (which still mirrors
the adblockparesr api) to be more efficient.

* Performance

Currently (with easylist), it seems like the average performance is somewhere
in-between adblock plus and ublock origin (about an overhead of ~0.2 ms per
request). However, there are a couple pathalogical cases which can cause the
latency to spike up to ~10ms.

Seeing as I only spent a couple hours optimizing this so far (aside from the
initial design), I think we can beat ubo if we have better balancing of filter
buckets (and even less reliance on python ~re~).

However, if you care about performance at all, you shouldn't be using a abp
style adblocker at all. even ~0.1ms overhead per request is extremely high,
considering that a trivial inefficient python host blocker is an order of
magnitude faster for almost the same results.

Here's an example of the overhead added for token generation (the absolute
minimum for every request), an optimal match, and a pathalogical case.

#+begin_example
-------------------------------------------------------------------------------------------- benchmark: 3 tests --------------------------------------------------------------------------------------------
Name (time in us)               Min                   Max                  Mean              StdDev                Median                 IQR            Outliers          OPS            Rounds  Iterations
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_token_str_bench        12.1200 (1.0)         30.1600 (1.0)         12.5919 (1.0)        0.7255 (1.0)         12.5000 (1.0)        0.1200 (1.0)     2468;4210  79,416.2722 (1.0)       55525           1
test_block[0]               35.0700 (2.89)        71.5200 (2.37)        38.5589 (3.06)       3.8416 (5.30)        36.3800 (2.91)       5.1900 (43.25)     268;156  25,934.3502 (0.33)       8930           1
test_pass[0]             1,693.7130 (139.75)   2,984.8430 (98.97)    1,786.6670 (141.89)   139.6831 (192.54)   1,723.5030 (137.88)   146.7500 (>1000.0)     42;13     559.7014 (0.01)        554           1
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#+end_example

Unfortunately, there's currently a regression from cpython when running with
pypy, as it looks like pypy is slower than cpython when running ~re~.

Performance of loading lists is abysmal currently, with loading easylist taking
about 2 seconds.

This is almost certainly extremely inefficient on memory, as I'm storing a ton
of debug information for no reason.

* Correctness

Honestly, I have no clue. There's not much in large datasets to compare against,
but this (at least) passes the examples in the abp spec.

I suspect there is some questionable logic in whitelisting domains.

* Features

Currently, I'm targeting a subset of the adblockplus filter spec. Right now, we
don't support (not an exhaustive list)

- ALL Element Hiding
- ~donottrack~
- ~match-case~
- ~rewrite~

I don't do any work to automatically detect host style lists at the moment
either.

Unsupported rules are silently ignored.

* Installation
** Dependencies
- ~python3~ or ~pypy3~
- ~attrs~
** Tests
- ~pytest-benchmark~

If you pass pep8, you fail the style tests.

** qutebrowser
This snippet in config.py seems to work for now on the git version of
qutebrowser, if you clone this repo in the config directory. It PULLS EASYLIST
FROM THIS REPO and not from the web. If you run ~:config-source~ it will reinit
everything, causing double latency and memory usage (so don't do it). Please
don't depend on anything here, it's all hacky and not done ~:]~.

most options won't be supported until [[https://github.com/qutebrowser/qutebrowser/pull/4525][this pull request]] is finalized.

#+begin_src python
  import sys, os
  sys.path.append(os.path.join(sys.path[0], 'jblock'))
  config.source("jblock/jblock/integrations/qutebrowser.py")
#+end_src

* Inspiration/Sources
- [[https://github.com/scrapinghub/adblockparser][adblockparser]]
- [[https://adblockplus.org/filter-cheatsheet#options][adblock filter cheatsheet]]
- [[https://adblockplus.org/en/filters][ABP filter doc]]
- [[https://adblockplus.org/blog/investigating-filter-matching-algorithms][(ABP) Investigating filter matching algorithms]]
- [[https://adblockplus.org/forum/viewtopic.php?t=6118][ABP faster filter matching]]
- [[https://github.com/ZhukovAlexander/triegex][triegex]]
- [[https://github.com/gorhill/uBlock/blob/master/src/js/static-net-filtering.js][uBlock filtering code]]
- [[https://github.com/gorhill/uBlock/wiki/Overview-of-uBlock's-network-filtering-engine][uBlock design doc]]
- [[https://github.com/adblockplus/adblockpluscore/blob/master/lib/matcher.js][ABP filtering code]]
- [[https://adblockplus.org/faq_internal][ABP internal faq]]
- [[https://www.loggly.com/blog/five-invaluable-techniques-to-improve-regex-performance/][Regexp performance tips]]
- [[https://github.com/gorhill/uBlock/blob/261ef8c510fd91ead57948d1f7793a7a5e2a25fd/src/js/utils.js][uBlock tokenizer]]
- [[https://github.com/gorhill/uBlock/wiki/uBlock-vs.-ABP:-efficiency-compared][ABP vs uBO latency]]

* License
jblock is licensed under the GPLv3+.

Some work was adapted from scrapinghub/adblockparser (which has almost all been
completely rewritten), but the combined work is GPLv3+.
